### ISSUE TITLE
Create About component

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/staff-picks#18]

**Comment by EdwinGuzman** [comment]
@courtneymcgee do you have the two link urls for: "patrons with print disabilities" and "About Best Books"?

**Comment by courtneymcgee** [comment]
@EdwinGuzman : 
https://www.nypl.org/accessibility/print-disabilities
https://www.nypl.org/books-music-dvds/recommendations/about/annual-lists

**Comment by rhernand3z** [comment]
Just spoke with @courtneymcgee and @ricardoom about this component. The issue I brought up was that the placement of the DOM on mobile v.s. desktop is totally different and will require:

1) to duplicate the DOM add css visuallyHidden classes appropriately (IMO DOM duplication does not adhere to a progressive application)
2) to manipulate the placement of the DOM with css possibly using position absolute which is hacky and IMO not ideal.

I brought up my concern because when we tackled the Header, many components had to be duplicated which congested the markup and added more css fixes for it to look different on various viewports. In a a11y/mobile first approach we should think about re-using markup progressively so that one single dom handles all viewports.

**Comment by EdwinGuzman** [comment]
Yup, thanks, that's what I was thinking and going for. Include me in the next discussions.
