### ISSUE TITLE
Is there a reason w/ the DTK Version being used is so behind the current release?

### ISSUE THREAD

**Issue by ricardoom** [NYPL/staff-picks#183]
https://github.com/NYPL/staff-picks/blob/6eb8c01eba4e25902cf6a9def596a0d6effca509/package.json#L48

**Comment by ktp242** [comment]
Following the suggestion from @ricardoom, we will update the version after a further notice.

**Comment by EdwinGuzman** [comment]
~~Laziness~~ Didn't fully discuss the repercussion of the narrower width from the updated version. But, we (@ricardogalvez and I) figured it was probably from the updates done on Discovery. Since the book card template will change and everything looks alright from an updated local installation, we can update the version anytime.

We could wait for final updates from the toolkit but I think we should just update it whenever a new version comes out and not have to make a ticket for ever minor version. Just add it as part of our workflow.

**Comment by ricardoom** [comment]
agreed. I'll close this issue then
